"""Nhóm ứng dụng mạng riêng ảo và quản lý thư viện phim nhạc."""

from model import App, password, port, text

ARR_ENV = {"PUID": "1000", "PGID": "1000", "TZ": "Asia/Ho_Chi_Minh"}

APPS = [
    App(
        key="tailscale", name="Tailscale", category="security",
        vi="Nối các máy của bạn thành một mạng riêng, xuyên qua NAT mà không cần mở cổng.",
        en="Joins your machines into one private network, punching through NAT with no open ports.",
        website="https://tailscale.com",
        image="tailscale/tailscale", tag_pages=6, min_major=1,
        volumes=("state:/var/lib/tailscale", "/dev/net/tun:/dev/net/tun"),
        fields=(
            password("AUTH_KEY", "Khóa xác thực", "Auth key",
                     help_vi="Tạo ở bảng điều khiển Tailscale, mục Settings › Keys.",
                     help_en="Create one in the Tailscale admin console under Settings › Keys."),
            text("NODE_NAME", "Tên máy trong mạng", "Machine name", "sunpanel"),
        ),
        environment={"TS_AUTHKEY": "${AUTH_KEY}", "TS_HOSTNAME": "${NODE_NAME}",
                     "TS_STATE_DIR": "/var/lib/tailscale", "TS_USERSPACE": "true"},
    ),
    App(
        key="headscale", name="Headscale", category="security",
        vi="Máy chủ điều phối thay cho dịch vụ Tailscale, để mạng riêng của bạn không phụ thuộc bên ngoài.",
        en="A self-hosted replacement for Tailscale's coordination server, so your private network depends on no one.",
        website="https://headscale.net",
        image="headscale/headscale", tag_pages=6, min_major=0,
        container_port=8080,
        command="serve",
        volumes=("config:/etc/headscale", "data:/var/lib/headscale"),
        fields=(port("HTTP_PORT", "Cổng", "Port", 8150),),
    ),
    App(
        key="netbird", name="NetBird", category="security",
        vi="Mạng riêng ngang hàng dựa trên WireGuard, có quản lý người dùng và quy tắc truy cập.",
        en="A peer-to-peer private network on WireGuard, with user management and access rules.",
        website="https://netbird.io",
        image="netbirdio/dashboard", tag_pages=6, min_major=2,
        container_port=80, volumes=(),
        fields=(
            port("HTTP_PORT", "Cổng web", "Web port", 8151),
            text("MGMT_URL", "Địa chỉ máy chủ quản lý", "Management server URL",
                 "http://localhost:33073"),
        ),
        environment={"NETBIRD_MGMT_API_ENDPOINT": "${MGMT_URL}"},
    ),
    App(
        key="zerotier", name="ZeroTier", category="security",
        vi="Mạng ảo phẳng nối mọi thiết bị như đang chung một switch, kể cả qua Internet.",
        en="A flat virtual network that makes every device act like it shares one switch, even across the Internet.",
        website="https://zerotier.com",
        image="zerotier/zerotier", tag_pages=6, min_major=1,
        volumes=("data:/var/lib/zerotier-one", "/dev/net/tun:/dev/net/tun"),
        fields=(
            text("NETWORK_ID", "Mã mạng", "Network ID", "",
                 help_vi="Mã 16 ký tự của mạng, lấy ở my.zerotier.com.",
                 help_en="The 16-character network ID from my.zerotier.com."),
        ),
        environment={"ZEROTIER_JOIN_NETWORKS": "${NETWORK_ID}"},
    ),
    App(
        key="lidarr", name="Lidarr", category="media",
        vi="Theo dõi nhạc theo nghệ sĩ: tự tải album mới và sắp xếp vào thư viện.",
        en="Follows music by artist: grabs new albums and organises them into the library.",
        website="https://lidarr.audio",
        image="linuxserver/lidarr", tag_pages=6, tag_any_suffix=True,
        container_port=8686,
        volumes=("config:/config", "${MUSIC_DIR}:/music", "${DOWNLOAD_DIR}:/downloads"),
        fields=(
            port("HTTP_PORT", "Cổng web", "Web port", 8686),
            text("MUSIC_DIR", "Thư mục nhạc", "Music folder", "/srv/music"),
            text("DOWNLOAD_DIR", "Thư mục tải về", "Download folder", "/srv/downloads"),
        ),
        environment=ARR_ENV,
    ),
    App(
        key="overseerr", name="Overseerr", category="media",
        vi="Trang nhận yêu cầu phim cho thư viện Plex, duyệt xong là hệ thống tự tải.",
        en="A media request page for Plex libraries — approve a request and the system fetches it.",
        website="https://overseerr.dev",
        image="linuxserver/overseerr", tag_pages=6, tag_any_suffix=True,
        container_port=5055, volumes=("config:/config",),
        fields=(port("HTTP_PORT", "Cổng web", "Web port", 5056),),
        environment=ARR_ENV,
    ),
    App(
        key="tautulli", name="Tautulli", category="media",
        vi="Thống kê ai xem gì trên Plex, xem bao lâu và từ thiết bị nào.",
        en="Statistics for Plex: who watched what, for how long and from which device.",
        website="https://tautulli.com",
        image="linuxserver/tautulli", tag_pages=6, tag_any_suffix=True,
        container_port=8181, volumes=("config:/config",),
        fields=(port("HTTP_PORT", "Cổng web", "Web port", 8182),),
        environment=ARR_ENV,
    ),
    App(
        key="unmanic", name="Unmanic", category="media",
        vi="Tự chuyển mã lại thư viện phim để đồng nhất định dạng và giảm dung lượng.",
        en="Re-encodes your media library to one consistent format and a smaller footprint.",
        website="https://docs.unmanic.app",
        image="josh5/unmanic", tag_pages=6, tag_any_suffix=True,
        container_port=8888,
        volumes=("config:/config", "${MEDIA_DIR}:/library", "cache:/tmp/unmanic"),
        fields=(
            port("HTTP_PORT", "Cổng web", "Web port", 8890),
            text("MEDIA_DIR", "Thư mục thư viện", "Library folder", "/srv/media"),
        ),
        environment=ARR_ENV,
    ),
    App(
        key="fileflows", name="FileFlows", category="media",
        vi="Dựng quy trình xử lý tệp bằng cách nối các khối: nhận diện, chuyển mã, di chuyển.",
        en="Builds file-processing pipelines by connecting blocks: detect, transcode, move.",
        website="https://fileflows.com",
        image="revenz/fileflows", tag_pages=6, min_major=1,
        container_port=5000,
        volumes=("data:/app/Data", "${MEDIA_DIR}:/media"),
        fields=(
            port("HTTP_PORT", "Cổng web", "Web port", 5030),
            text("MEDIA_DIR", "Thư mục thư viện", "Library folder", "/srv/media"),
        ),
        environment={"TZ": "Asia/Ho_Chi_Minh"},
    ),
    App(
        key="handbrake", name="HandBrake", category="media",
        vi="Chuyển mã video qua giao diện web, có sẵn hàng chục cấu hình dựng sẵn.",
        en="Video transcoding through a web UI, with dozens of ready-made presets.",
        website="https://handbrake.fr",
        image="jlesage/handbrake", tag_pages=6, min_major=1,
        container_port=5800,
        volumes=("config:/config", "${MEDIA_DIR}:/storage:ro", "${OUTPUT_DIR}:/output"),
        fields=(
            port("HTTP_PORT", "Cổng web", "Web port", 5801),
            text("MEDIA_DIR", "Thư mục nguồn", "Source folder", "/srv/media"),
            text("OUTPUT_DIR", "Thư mục kết quả", "Output folder", "/srv/media/converted"),
        ),
        environment={"TZ": "Asia/Ho_Chi_Minh"},
    ),
    App(
        key="mkvtoolnix", name="MKVToolNix", category="media",
        vi="Ghép, tách và sửa thông tin tệp MKV: đổi phụ đề, đổi tên rãnh, gộp nhiều nguồn.",
        en="Merges, splits and edits MKV files: swap subtitles, rename tracks, combine sources.",
        website="https://mkvtoolnix.download",
        image="jlesage/mkvtoolnix", tag_pages=6, min_major=1,
        container_port=5800,
        volumes=("config:/config", "${MEDIA_DIR}:/storage"),
        fields=(
            port("HTTP_PORT", "Cổng web", "Web port", 5802),
            text("MEDIA_DIR", "Thư mục làm việc", "Working folder", "/srv/media"),
        ),
        environment={"TZ": "Asia/Ho_Chi_Minh"},
    ),
]
